
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Rates` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Rates
 * 
 */
export type RatesModel = runtime.Types.Result.DefaultSelection<Prisma.$RatesPayload>

export type AggregateRates = {
  _count: RatesCountAggregateOutputType | null
  _avg: RatesAvgAggregateOutputType | null
  _sum: RatesSumAggregateOutputType | null
  _min: RatesMinAggregateOutputType | null
  _max: RatesMaxAggregateOutputType | null
}

export type RatesAvgAggregateOutputType = {
  nightly: number | null
  weekly: number | null
  monthly: number | null
  yearly: number | null
}

export type RatesSumAggregateOutputType = {
  nightly: number | null
  weekly: number | null
  monthly: number | null
  yearly: number | null
}

export type RatesMinAggregateOutputType = {
  id: string | null
  nightly: number | null
  weekly: number | null
  monthly: number | null
  yearly: number | null
}

export type RatesMaxAggregateOutputType = {
  id: string | null
  nightly: number | null
  weekly: number | null
  monthly: number | null
  yearly: number | null
}

export type RatesCountAggregateOutputType = {
  id: number
  nightly: number
  weekly: number
  monthly: number
  yearly: number
  _all: number
}


export type RatesAvgAggregateInputType = {
  nightly?: true
  weekly?: true
  monthly?: true
  yearly?: true
}

export type RatesSumAggregateInputType = {
  nightly?: true
  weekly?: true
  monthly?: true
  yearly?: true
}

export type RatesMinAggregateInputType = {
  id?: true
  nightly?: true
  weekly?: true
  monthly?: true
  yearly?: true
}

export type RatesMaxAggregateInputType = {
  id?: true
  nightly?: true
  weekly?: true
  monthly?: true
  yearly?: true
}

export type RatesCountAggregateInputType = {
  id?: true
  nightly?: true
  weekly?: true
  monthly?: true
  yearly?: true
  _all?: true
}

export type RatesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Rates to aggregate.
   */
  where?: Prisma.RatesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Rates to fetch.
   */
  orderBy?: Prisma.RatesOrderByWithRelationInput | Prisma.RatesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RatesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Rates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Rates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Rates
  **/
  _count?: true | RatesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RatesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RatesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RatesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RatesMaxAggregateInputType
}

export type GetRatesAggregateType<T extends RatesAggregateArgs> = {
      [P in keyof T & keyof AggregateRates]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRates[P]>
    : Prisma.GetScalarType<T[P], AggregateRates[P]>
}




export type RatesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RatesWhereInput
  orderBy?: Prisma.RatesOrderByWithAggregationInput | Prisma.RatesOrderByWithAggregationInput[]
  by: Prisma.RatesScalarFieldEnum[] | Prisma.RatesScalarFieldEnum
  having?: Prisma.RatesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RatesCountAggregateInputType | true
  _avg?: RatesAvgAggregateInputType
  _sum?: RatesSumAggregateInputType
  _min?: RatesMinAggregateInputType
  _max?: RatesMaxAggregateInputType
}

export type RatesGroupByOutputType = {
  id: string
  nightly: number | null
  weekly: number | null
  monthly: number | null
  yearly: number | null
  _count: RatesCountAggregateOutputType | null
  _avg: RatesAvgAggregateOutputType | null
  _sum: RatesSumAggregateOutputType | null
  _min: RatesMinAggregateOutputType | null
  _max: RatesMaxAggregateOutputType | null
}

type GetRatesGroupByPayload<T extends RatesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RatesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RatesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RatesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RatesGroupByOutputType[P]>
      }
    >
  >



export type RatesWhereInput = {
  AND?: Prisma.RatesWhereInput | Prisma.RatesWhereInput[]
  OR?: Prisma.RatesWhereInput[]
  NOT?: Prisma.RatesWhereInput | Prisma.RatesWhereInput[]
  id?: Prisma.StringFilter<"Rates"> | string
  nightly?: Prisma.IntNullableFilter<"Rates"> | number | null
  weekly?: Prisma.IntNullableFilter<"Rates"> | number | null
  monthly?: Prisma.IntNullableFilter<"Rates"> | number | null
  yearly?: Prisma.IntNullableFilter<"Rates"> | number | null
  property?: Prisma.XOR<Prisma.PropertyNullableScalarRelationFilter, Prisma.PropertyWhereInput> | null
}

export type RatesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nightly?: Prisma.SortOrderInput | Prisma.SortOrder
  weekly?: Prisma.SortOrderInput | Prisma.SortOrder
  monthly?: Prisma.SortOrderInput | Prisma.SortOrder
  yearly?: Prisma.SortOrderInput | Prisma.SortOrder
  property?: Prisma.PropertyOrderByWithRelationInput
}

export type RatesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.RatesWhereInput | Prisma.RatesWhereInput[]
  OR?: Prisma.RatesWhereInput[]
  NOT?: Prisma.RatesWhereInput | Prisma.RatesWhereInput[]
  nightly?: Prisma.IntNullableFilter<"Rates"> | number | null
  weekly?: Prisma.IntNullableFilter<"Rates"> | number | null
  monthly?: Prisma.IntNullableFilter<"Rates"> | number | null
  yearly?: Prisma.IntNullableFilter<"Rates"> | number | null
  property?: Prisma.XOR<Prisma.PropertyNullableScalarRelationFilter, Prisma.PropertyWhereInput> | null
}, "id">

export type RatesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nightly?: Prisma.SortOrderInput | Prisma.SortOrder
  weekly?: Prisma.SortOrderInput | Prisma.SortOrder
  monthly?: Prisma.SortOrderInput | Prisma.SortOrder
  yearly?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.RatesCountOrderByAggregateInput
  _avg?: Prisma.RatesAvgOrderByAggregateInput
  _max?: Prisma.RatesMaxOrderByAggregateInput
  _min?: Prisma.RatesMinOrderByAggregateInput
  _sum?: Prisma.RatesSumOrderByAggregateInput
}

export type RatesScalarWhereWithAggregatesInput = {
  AND?: Prisma.RatesScalarWhereWithAggregatesInput | Prisma.RatesScalarWhereWithAggregatesInput[]
  OR?: Prisma.RatesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RatesScalarWhereWithAggregatesInput | Prisma.RatesScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Rates"> | string
  nightly?: Prisma.IntNullableWithAggregatesFilter<"Rates"> | number | null
  weekly?: Prisma.IntNullableWithAggregatesFilter<"Rates"> | number | null
  monthly?: Prisma.IntNullableWithAggregatesFilter<"Rates"> | number | null
  yearly?: Prisma.IntNullableWithAggregatesFilter<"Rates"> | number | null
}

export type RatesCreateInput = {
  id?: string
  nightly?: number | null
  weekly?: number | null
  monthly?: number | null
  yearly?: number | null
  property?: Prisma.PropertyCreateNestedOneWithoutRatesInput
}

export type RatesUncheckedCreateInput = {
  id?: string
  nightly?: number | null
  weekly?: number | null
  monthly?: number | null
  yearly?: number | null
  property?: Prisma.PropertyUncheckedCreateNestedOneWithoutRatesInput
}

export type RatesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nightly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  weekly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  monthly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yearly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  property?: Prisma.PropertyUpdateOneWithoutRatesNestedInput
}

export type RatesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nightly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  weekly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  monthly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yearly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  property?: Prisma.PropertyUncheckedUpdateOneWithoutRatesNestedInput
}

export type RatesCreateManyInput = {
  id?: string
  nightly?: number | null
  weekly?: number | null
  monthly?: number | null
  yearly?: number | null
}

export type RatesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nightly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  weekly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  monthly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yearly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type RatesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nightly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  weekly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  monthly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yearly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type RatesScalarRelationFilter = {
  is?: Prisma.RatesWhereInput
  isNot?: Prisma.RatesWhereInput
}

export type RatesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nightly?: Prisma.SortOrder
  weekly?: Prisma.SortOrder
  monthly?: Prisma.SortOrder
  yearly?: Prisma.SortOrder
}

export type RatesAvgOrderByAggregateInput = {
  nightly?: Prisma.SortOrder
  weekly?: Prisma.SortOrder
  monthly?: Prisma.SortOrder
  yearly?: Prisma.SortOrder
}

export type RatesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nightly?: Prisma.SortOrder
  weekly?: Prisma.SortOrder
  monthly?: Prisma.SortOrder
  yearly?: Prisma.SortOrder
}

export type RatesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nightly?: Prisma.SortOrder
  weekly?: Prisma.SortOrder
  monthly?: Prisma.SortOrder
  yearly?: Prisma.SortOrder
}

export type RatesSumOrderByAggregateInput = {
  nightly?: Prisma.SortOrder
  weekly?: Prisma.SortOrder
  monthly?: Prisma.SortOrder
  yearly?: Prisma.SortOrder
}

export type RatesCreateNestedOneWithoutPropertyInput = {
  create?: Prisma.XOR<Prisma.RatesCreateWithoutPropertyInput, Prisma.RatesUncheckedCreateWithoutPropertyInput>
  connectOrCreate?: Prisma.RatesCreateOrConnectWithoutPropertyInput
  connect?: Prisma.RatesWhereUniqueInput
}

export type RatesUpdateOneRequiredWithoutPropertyNestedInput = {
  create?: Prisma.XOR<Prisma.RatesCreateWithoutPropertyInput, Prisma.RatesUncheckedCreateWithoutPropertyInput>
  connectOrCreate?: Prisma.RatesCreateOrConnectWithoutPropertyInput
  upsert?: Prisma.RatesUpsertWithoutPropertyInput
  connect?: Prisma.RatesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RatesUpdateToOneWithWhereWithoutPropertyInput, Prisma.RatesUpdateWithoutPropertyInput>, Prisma.RatesUncheckedUpdateWithoutPropertyInput>
}

export type RatesCreateWithoutPropertyInput = {
  id?: string
  nightly?: number | null
  weekly?: number | null
  monthly?: number | null
  yearly?: number | null
}

export type RatesUncheckedCreateWithoutPropertyInput = {
  id?: string
  nightly?: number | null
  weekly?: number | null
  monthly?: number | null
  yearly?: number | null
}

export type RatesCreateOrConnectWithoutPropertyInput = {
  where: Prisma.RatesWhereUniqueInput
  create: Prisma.XOR<Prisma.RatesCreateWithoutPropertyInput, Prisma.RatesUncheckedCreateWithoutPropertyInput>
}

export type RatesUpsertWithoutPropertyInput = {
  update: Prisma.XOR<Prisma.RatesUpdateWithoutPropertyInput, Prisma.RatesUncheckedUpdateWithoutPropertyInput>
  create: Prisma.XOR<Prisma.RatesCreateWithoutPropertyInput, Prisma.RatesUncheckedCreateWithoutPropertyInput>
  where?: Prisma.RatesWhereInput
}

export type RatesUpdateToOneWithWhereWithoutPropertyInput = {
  where?: Prisma.RatesWhereInput
  data: Prisma.XOR<Prisma.RatesUpdateWithoutPropertyInput, Prisma.RatesUncheckedUpdateWithoutPropertyInput>
}

export type RatesUpdateWithoutPropertyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nightly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  weekly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  monthly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yearly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type RatesUncheckedUpdateWithoutPropertyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nightly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  weekly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  monthly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  yearly?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}



export type RatesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nightly?: boolean
  weekly?: boolean
  monthly?: boolean
  yearly?: boolean
  property?: boolean | Prisma.Rates$propertyArgs<ExtArgs>
}, ExtArgs["result"]["rates"]>

export type RatesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nightly?: boolean
  weekly?: boolean
  monthly?: boolean
  yearly?: boolean
}, ExtArgs["result"]["rates"]>

export type RatesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nightly?: boolean
  weekly?: boolean
  monthly?: boolean
  yearly?: boolean
}, ExtArgs["result"]["rates"]>

export type RatesSelectScalar = {
  id?: boolean
  nightly?: boolean
  weekly?: boolean
  monthly?: boolean
  yearly?: boolean
}

export type RatesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nightly" | "weekly" | "monthly" | "yearly", ExtArgs["result"]["rates"]>
export type RatesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  property?: boolean | Prisma.Rates$propertyArgs<ExtArgs>
}
export type RatesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type RatesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $RatesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Rates"
  objects: {
    property: Prisma.$PropertyPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    nightly: number | null
    weekly: number | null
    monthly: number | null
    yearly: number | null
  }, ExtArgs["result"]["rates"]>
  composites: {}
}

export type RatesGetPayload<S extends boolean | null | undefined | RatesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RatesPayload, S>

export type RatesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RatesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RatesCountAggregateInputType | true
  }

export interface RatesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Rates'], meta: { name: 'Rates' } }
  /**
   * Find zero or one Rates that matches the filter.
   * @param {RatesFindUniqueArgs} args - Arguments to find a Rates
   * @example
   * // Get one Rates
   * const rates = await prisma.rates.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RatesFindUniqueArgs>(args: Prisma.SelectSubset<T, RatesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RatesClient<runtime.Types.Result.GetResult<Prisma.$RatesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Rates that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RatesFindUniqueOrThrowArgs} args - Arguments to find a Rates
   * @example
   * // Get one Rates
   * const rates = await prisma.rates.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RatesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RatesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RatesClient<runtime.Types.Result.GetResult<Prisma.$RatesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Rates that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RatesFindFirstArgs} args - Arguments to find a Rates
   * @example
   * // Get one Rates
   * const rates = await prisma.rates.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RatesFindFirstArgs>(args?: Prisma.SelectSubset<T, RatesFindFirstArgs<ExtArgs>>): Prisma.Prisma__RatesClient<runtime.Types.Result.GetResult<Prisma.$RatesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Rates that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RatesFindFirstOrThrowArgs} args - Arguments to find a Rates
   * @example
   * // Get one Rates
   * const rates = await prisma.rates.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RatesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RatesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RatesClient<runtime.Types.Result.GetResult<Prisma.$RatesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Rates that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RatesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Rates
   * const rates = await prisma.rates.findMany()
   * 
   * // Get first 10 Rates
   * const rates = await prisma.rates.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const ratesWithIdOnly = await prisma.rates.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RatesFindManyArgs>(args?: Prisma.SelectSubset<T, RatesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RatesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Rates.
   * @param {RatesCreateArgs} args - Arguments to create a Rates.
   * @example
   * // Create one Rates
   * const Rates = await prisma.rates.create({
   *   data: {
   *     // ... data to create a Rates
   *   }
   * })
   * 
   */
  create<T extends RatesCreateArgs>(args: Prisma.SelectSubset<T, RatesCreateArgs<ExtArgs>>): Prisma.Prisma__RatesClient<runtime.Types.Result.GetResult<Prisma.$RatesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Rates.
   * @param {RatesCreateManyArgs} args - Arguments to create many Rates.
   * @example
   * // Create many Rates
   * const rates = await prisma.rates.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RatesCreateManyArgs>(args?: Prisma.SelectSubset<T, RatesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Rates and returns the data saved in the database.
   * @param {RatesCreateManyAndReturnArgs} args - Arguments to create many Rates.
   * @example
   * // Create many Rates
   * const rates = await prisma.rates.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Rates and only return the `id`
   * const ratesWithIdOnly = await prisma.rates.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RatesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RatesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RatesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Rates.
   * @param {RatesDeleteArgs} args - Arguments to delete one Rates.
   * @example
   * // Delete one Rates
   * const Rates = await prisma.rates.delete({
   *   where: {
   *     // ... filter to delete one Rates
   *   }
   * })
   * 
   */
  delete<T extends RatesDeleteArgs>(args: Prisma.SelectSubset<T, RatesDeleteArgs<ExtArgs>>): Prisma.Prisma__RatesClient<runtime.Types.Result.GetResult<Prisma.$RatesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Rates.
   * @param {RatesUpdateArgs} args - Arguments to update one Rates.
   * @example
   * // Update one Rates
   * const rates = await prisma.rates.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RatesUpdateArgs>(args: Prisma.SelectSubset<T, RatesUpdateArgs<ExtArgs>>): Prisma.Prisma__RatesClient<runtime.Types.Result.GetResult<Prisma.$RatesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Rates.
   * @param {RatesDeleteManyArgs} args - Arguments to filter Rates to delete.
   * @example
   * // Delete a few Rates
   * const { count } = await prisma.rates.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RatesDeleteManyArgs>(args?: Prisma.SelectSubset<T, RatesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Rates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RatesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Rates
   * const rates = await prisma.rates.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RatesUpdateManyArgs>(args: Prisma.SelectSubset<T, RatesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Rates and returns the data updated in the database.
   * @param {RatesUpdateManyAndReturnArgs} args - Arguments to update many Rates.
   * @example
   * // Update many Rates
   * const rates = await prisma.rates.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Rates and only return the `id`
   * const ratesWithIdOnly = await prisma.rates.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RatesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RatesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RatesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Rates.
   * @param {RatesUpsertArgs} args - Arguments to update or create a Rates.
   * @example
   * // Update or create a Rates
   * const rates = await prisma.rates.upsert({
   *   create: {
   *     // ... data to create a Rates
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Rates we want to update
   *   }
   * })
   */
  upsert<T extends RatesUpsertArgs>(args: Prisma.SelectSubset<T, RatesUpsertArgs<ExtArgs>>): Prisma.Prisma__RatesClient<runtime.Types.Result.GetResult<Prisma.$RatesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Rates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RatesCountArgs} args - Arguments to filter Rates to count.
   * @example
   * // Count the number of Rates
   * const count = await prisma.rates.count({
   *   where: {
   *     // ... the filter for the Rates we want to count
   *   }
   * })
  **/
  count<T extends RatesCountArgs>(
    args?: Prisma.Subset<T, RatesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RatesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Rates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RatesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RatesAggregateArgs>(args: Prisma.Subset<T, RatesAggregateArgs>): Prisma.PrismaPromise<GetRatesAggregateType<T>>

  /**
   * Group by Rates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RatesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RatesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RatesGroupByArgs['orderBy'] }
      : { orderBy?: RatesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RatesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRatesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Rates model
 */
readonly fields: RatesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Rates.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RatesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  property<T extends Prisma.Rates$propertyArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Rates$propertyArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Rates model
 */
export interface RatesFieldRefs {
  readonly id: Prisma.FieldRef<"Rates", 'String'>
  readonly nightly: Prisma.FieldRef<"Rates", 'Int'>
  readonly weekly: Prisma.FieldRef<"Rates", 'Int'>
  readonly monthly: Prisma.FieldRef<"Rates", 'Int'>
  readonly yearly: Prisma.FieldRef<"Rates", 'Int'>
}
    

// Custom InputTypes
/**
 * Rates findUnique
 */
export type RatesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Rates
   */
  select?: Prisma.RatesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Rates
   */
  omit?: Prisma.RatesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RatesInclude<ExtArgs> | null
  /**
   * Filter, which Rates to fetch.
   */
  where: Prisma.RatesWhereUniqueInput
}

/**
 * Rates findUniqueOrThrow
 */
export type RatesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Rates
   */
  select?: Prisma.RatesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Rates
   */
  omit?: Prisma.RatesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RatesInclude<ExtArgs> | null
  /**
   * Filter, which Rates to fetch.
   */
  where: Prisma.RatesWhereUniqueInput
}

/**
 * Rates findFirst
 */
export type RatesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Rates
   */
  select?: Prisma.RatesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Rates
   */
  omit?: Prisma.RatesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RatesInclude<ExtArgs> | null
  /**
   * Filter, which Rates to fetch.
   */
  where?: Prisma.RatesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Rates to fetch.
   */
  orderBy?: Prisma.RatesOrderByWithRelationInput | Prisma.RatesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Rates.
   */
  cursor?: Prisma.RatesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Rates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Rates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Rates.
   */
  distinct?: Prisma.RatesScalarFieldEnum | Prisma.RatesScalarFieldEnum[]
}

/**
 * Rates findFirstOrThrow
 */
export type RatesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Rates
   */
  select?: Prisma.RatesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Rates
   */
  omit?: Prisma.RatesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RatesInclude<ExtArgs> | null
  /**
   * Filter, which Rates to fetch.
   */
  where?: Prisma.RatesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Rates to fetch.
   */
  orderBy?: Prisma.RatesOrderByWithRelationInput | Prisma.RatesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Rates.
   */
  cursor?: Prisma.RatesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Rates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Rates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Rates.
   */
  distinct?: Prisma.RatesScalarFieldEnum | Prisma.RatesScalarFieldEnum[]
}

/**
 * Rates findMany
 */
export type RatesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Rates
   */
  select?: Prisma.RatesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Rates
   */
  omit?: Prisma.RatesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RatesInclude<ExtArgs> | null
  /**
   * Filter, which Rates to fetch.
   */
  where?: Prisma.RatesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Rates to fetch.
   */
  orderBy?: Prisma.RatesOrderByWithRelationInput | Prisma.RatesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Rates.
   */
  cursor?: Prisma.RatesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Rates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Rates.
   */
  skip?: number
  distinct?: Prisma.RatesScalarFieldEnum | Prisma.RatesScalarFieldEnum[]
}

/**
 * Rates create
 */
export type RatesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Rates
   */
  select?: Prisma.RatesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Rates
   */
  omit?: Prisma.RatesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RatesInclude<ExtArgs> | null
  /**
   * The data needed to create a Rates.
   */
  data?: Prisma.XOR<Prisma.RatesCreateInput, Prisma.RatesUncheckedCreateInput>
}

/**
 * Rates createMany
 */
export type RatesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Rates.
   */
  data: Prisma.RatesCreateManyInput | Prisma.RatesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Rates createManyAndReturn
 */
export type RatesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Rates
   */
  select?: Prisma.RatesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Rates
   */
  omit?: Prisma.RatesOmit<ExtArgs> | null
  /**
   * The data used to create many Rates.
   */
  data: Prisma.RatesCreateManyInput | Prisma.RatesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Rates update
 */
export type RatesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Rates
   */
  select?: Prisma.RatesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Rates
   */
  omit?: Prisma.RatesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RatesInclude<ExtArgs> | null
  /**
   * The data needed to update a Rates.
   */
  data: Prisma.XOR<Prisma.RatesUpdateInput, Prisma.RatesUncheckedUpdateInput>
  /**
   * Choose, which Rates to update.
   */
  where: Prisma.RatesWhereUniqueInput
}

/**
 * Rates updateMany
 */
export type RatesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Rates.
   */
  data: Prisma.XOR<Prisma.RatesUpdateManyMutationInput, Prisma.RatesUncheckedUpdateManyInput>
  /**
   * Filter which Rates to update
   */
  where?: Prisma.RatesWhereInput
  /**
   * Limit how many Rates to update.
   */
  limit?: number
}

/**
 * Rates updateManyAndReturn
 */
export type RatesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Rates
   */
  select?: Prisma.RatesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Rates
   */
  omit?: Prisma.RatesOmit<ExtArgs> | null
  /**
   * The data used to update Rates.
   */
  data: Prisma.XOR<Prisma.RatesUpdateManyMutationInput, Prisma.RatesUncheckedUpdateManyInput>
  /**
   * Filter which Rates to update
   */
  where?: Prisma.RatesWhereInput
  /**
   * Limit how many Rates to update.
   */
  limit?: number
}

/**
 * Rates upsert
 */
export type RatesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Rates
   */
  select?: Prisma.RatesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Rates
   */
  omit?: Prisma.RatesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RatesInclude<ExtArgs> | null
  /**
   * The filter to search for the Rates to update in case it exists.
   */
  where: Prisma.RatesWhereUniqueInput
  /**
   * In case the Rates found by the `where` argument doesn't exist, create a new Rates with this data.
   */
  create: Prisma.XOR<Prisma.RatesCreateInput, Prisma.RatesUncheckedCreateInput>
  /**
   * In case the Rates was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RatesUpdateInput, Prisma.RatesUncheckedUpdateInput>
}

/**
 * Rates delete
 */
export type RatesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Rates
   */
  select?: Prisma.RatesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Rates
   */
  omit?: Prisma.RatesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RatesInclude<ExtArgs> | null
  /**
   * Filter which Rates to delete.
   */
  where: Prisma.RatesWhereUniqueInput
}

/**
 * Rates deleteMany
 */
export type RatesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Rates to delete
   */
  where?: Prisma.RatesWhereInput
  /**
   * Limit how many Rates to delete.
   */
  limit?: number
}

/**
 * Rates.property
 */
export type Rates$propertyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  where?: Prisma.PropertyWhereInput
}

/**
 * Rates without action
 */
export type RatesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Rates
   */
  select?: Prisma.RatesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Rates
   */
  omit?: Prisma.RatesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RatesInclude<ExtArgs> | null
}
