
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SellerInfo` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SellerInfo
 * 
 */
export type SellerInfoModel = runtime.Types.Result.DefaultSelection<Prisma.$SellerInfoPayload>

export type AggregateSellerInfo = {
  _count: SellerInfoCountAggregateOutputType | null
  _min: SellerInfoMinAggregateOutputType | null
  _max: SellerInfoMaxAggregateOutputType | null
}

export type SellerInfoMinAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  phone: string | null
}

export type SellerInfoMaxAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  phone: string | null
}

export type SellerInfoCountAggregateOutputType = {
  id: number
  name: number
  email: number
  phone: number
  _all: number
}


export type SellerInfoMinAggregateInputType = {
  id?: true
  name?: true
  email?: true
  phone?: true
}

export type SellerInfoMaxAggregateInputType = {
  id?: true
  name?: true
  email?: true
  phone?: true
}

export type SellerInfoCountAggregateInputType = {
  id?: true
  name?: true
  email?: true
  phone?: true
  _all?: true
}

export type SellerInfoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SellerInfo to aggregate.
   */
  where?: Prisma.SellerInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SellerInfos to fetch.
   */
  orderBy?: Prisma.SellerInfoOrderByWithRelationInput | Prisma.SellerInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SellerInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SellerInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SellerInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SellerInfos
  **/
  _count?: true | SellerInfoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SellerInfoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SellerInfoMaxAggregateInputType
}

export type GetSellerInfoAggregateType<T extends SellerInfoAggregateArgs> = {
      [P in keyof T & keyof AggregateSellerInfo]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSellerInfo[P]>
    : Prisma.GetScalarType<T[P], AggregateSellerInfo[P]>
}




export type SellerInfoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SellerInfoWhereInput
  orderBy?: Prisma.SellerInfoOrderByWithAggregationInput | Prisma.SellerInfoOrderByWithAggregationInput[]
  by: Prisma.SellerInfoScalarFieldEnum[] | Prisma.SellerInfoScalarFieldEnum
  having?: Prisma.SellerInfoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SellerInfoCountAggregateInputType | true
  _min?: SellerInfoMinAggregateInputType
  _max?: SellerInfoMaxAggregateInputType
}

export type SellerInfoGroupByOutputType = {
  id: string
  name: string
  email: string
  phone: string
  _count: SellerInfoCountAggregateOutputType | null
  _min: SellerInfoMinAggregateOutputType | null
  _max: SellerInfoMaxAggregateOutputType | null
}

type GetSellerInfoGroupByPayload<T extends SellerInfoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SellerInfoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SellerInfoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SellerInfoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SellerInfoGroupByOutputType[P]>
      }
    >
  >



export type SellerInfoWhereInput = {
  AND?: Prisma.SellerInfoWhereInput | Prisma.SellerInfoWhereInput[]
  OR?: Prisma.SellerInfoWhereInput[]
  NOT?: Prisma.SellerInfoWhereInput | Prisma.SellerInfoWhereInput[]
  id?: Prisma.StringFilter<"SellerInfo"> | string
  name?: Prisma.StringFilter<"SellerInfo"> | string
  email?: Prisma.StringFilter<"SellerInfo"> | string
  phone?: Prisma.StringFilter<"SellerInfo"> | string
  property?: Prisma.XOR<Prisma.PropertyNullableScalarRelationFilter, Prisma.PropertyWhereInput> | null
}

export type SellerInfoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  property?: Prisma.PropertyOrderByWithRelationInput
}

export type SellerInfoWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SellerInfoWhereInput | Prisma.SellerInfoWhereInput[]
  OR?: Prisma.SellerInfoWhereInput[]
  NOT?: Prisma.SellerInfoWhereInput | Prisma.SellerInfoWhereInput[]
  name?: Prisma.StringFilter<"SellerInfo"> | string
  email?: Prisma.StringFilter<"SellerInfo"> | string
  phone?: Prisma.StringFilter<"SellerInfo"> | string
  property?: Prisma.XOR<Prisma.PropertyNullableScalarRelationFilter, Prisma.PropertyWhereInput> | null
}, "id">

export type SellerInfoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  _count?: Prisma.SellerInfoCountOrderByAggregateInput
  _max?: Prisma.SellerInfoMaxOrderByAggregateInput
  _min?: Prisma.SellerInfoMinOrderByAggregateInput
}

export type SellerInfoScalarWhereWithAggregatesInput = {
  AND?: Prisma.SellerInfoScalarWhereWithAggregatesInput | Prisma.SellerInfoScalarWhereWithAggregatesInput[]
  OR?: Prisma.SellerInfoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SellerInfoScalarWhereWithAggregatesInput | Prisma.SellerInfoScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SellerInfo"> | string
  name?: Prisma.StringWithAggregatesFilter<"SellerInfo"> | string
  email?: Prisma.StringWithAggregatesFilter<"SellerInfo"> | string
  phone?: Prisma.StringWithAggregatesFilter<"SellerInfo"> | string
}

export type SellerInfoCreateInput = {
  id?: string
  name: string
  email: string
  phone: string
  property?: Prisma.PropertyCreateNestedOneWithoutSellerInfoInput
}

export type SellerInfoUncheckedCreateInput = {
  id?: string
  name: string
  email: string
  phone: string
  property?: Prisma.PropertyUncheckedCreateNestedOneWithoutSellerInfoInput
}

export type SellerInfoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  property?: Prisma.PropertyUpdateOneWithoutSellerInfoNestedInput
}

export type SellerInfoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  property?: Prisma.PropertyUncheckedUpdateOneWithoutSellerInfoNestedInput
}

export type SellerInfoCreateManyInput = {
  id?: string
  name: string
  email: string
  phone: string
}

export type SellerInfoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SellerInfoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SellerInfoScalarRelationFilter = {
  is?: Prisma.SellerInfoWhereInput
  isNot?: Prisma.SellerInfoWhereInput
}

export type SellerInfoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
}

export type SellerInfoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
}

export type SellerInfoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
}

export type SellerInfoCreateNestedOneWithoutPropertyInput = {
  create?: Prisma.XOR<Prisma.SellerInfoCreateWithoutPropertyInput, Prisma.SellerInfoUncheckedCreateWithoutPropertyInput>
  connectOrCreate?: Prisma.SellerInfoCreateOrConnectWithoutPropertyInput
  connect?: Prisma.SellerInfoWhereUniqueInput
}

export type SellerInfoUpdateOneRequiredWithoutPropertyNestedInput = {
  create?: Prisma.XOR<Prisma.SellerInfoCreateWithoutPropertyInput, Prisma.SellerInfoUncheckedCreateWithoutPropertyInput>
  connectOrCreate?: Prisma.SellerInfoCreateOrConnectWithoutPropertyInput
  upsert?: Prisma.SellerInfoUpsertWithoutPropertyInput
  connect?: Prisma.SellerInfoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SellerInfoUpdateToOneWithWhereWithoutPropertyInput, Prisma.SellerInfoUpdateWithoutPropertyInput>, Prisma.SellerInfoUncheckedUpdateWithoutPropertyInput>
}

export type SellerInfoCreateWithoutPropertyInput = {
  id?: string
  name: string
  email: string
  phone: string
}

export type SellerInfoUncheckedCreateWithoutPropertyInput = {
  id?: string
  name: string
  email: string
  phone: string
}

export type SellerInfoCreateOrConnectWithoutPropertyInput = {
  where: Prisma.SellerInfoWhereUniqueInput
  create: Prisma.XOR<Prisma.SellerInfoCreateWithoutPropertyInput, Prisma.SellerInfoUncheckedCreateWithoutPropertyInput>
}

export type SellerInfoUpsertWithoutPropertyInput = {
  update: Prisma.XOR<Prisma.SellerInfoUpdateWithoutPropertyInput, Prisma.SellerInfoUncheckedUpdateWithoutPropertyInput>
  create: Prisma.XOR<Prisma.SellerInfoCreateWithoutPropertyInput, Prisma.SellerInfoUncheckedCreateWithoutPropertyInput>
  where?: Prisma.SellerInfoWhereInput
}

export type SellerInfoUpdateToOneWithWhereWithoutPropertyInput = {
  where?: Prisma.SellerInfoWhereInput
  data: Prisma.XOR<Prisma.SellerInfoUpdateWithoutPropertyInput, Prisma.SellerInfoUncheckedUpdateWithoutPropertyInput>
}

export type SellerInfoUpdateWithoutPropertyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SellerInfoUncheckedUpdateWithoutPropertyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
}



export type SellerInfoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  phone?: boolean
  property?: boolean | Prisma.SellerInfo$propertyArgs<ExtArgs>
}, ExtArgs["result"]["sellerInfo"]>

export type SellerInfoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  phone?: boolean
}, ExtArgs["result"]["sellerInfo"]>

export type SellerInfoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  phone?: boolean
}, ExtArgs["result"]["sellerInfo"]>

export type SellerInfoSelectScalar = {
  id?: boolean
  name?: boolean
  email?: boolean
  phone?: boolean
}

export type SellerInfoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "email" | "phone", ExtArgs["result"]["sellerInfo"]>
export type SellerInfoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  property?: boolean | Prisma.SellerInfo$propertyArgs<ExtArgs>
}
export type SellerInfoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type SellerInfoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $SellerInfoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SellerInfo"
  objects: {
    property: Prisma.$PropertyPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    email: string
    phone: string
  }, ExtArgs["result"]["sellerInfo"]>
  composites: {}
}

export type SellerInfoGetPayload<S extends boolean | null | undefined | SellerInfoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SellerInfoPayload, S>

export type SellerInfoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SellerInfoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SellerInfoCountAggregateInputType | true
  }

export interface SellerInfoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SellerInfo'], meta: { name: 'SellerInfo' } }
  /**
   * Find zero or one SellerInfo that matches the filter.
   * @param {SellerInfoFindUniqueArgs} args - Arguments to find a SellerInfo
   * @example
   * // Get one SellerInfo
   * const sellerInfo = await prisma.sellerInfo.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SellerInfoFindUniqueArgs>(args: Prisma.SelectSubset<T, SellerInfoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SellerInfoClient<runtime.Types.Result.GetResult<Prisma.$SellerInfoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SellerInfo that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SellerInfoFindUniqueOrThrowArgs} args - Arguments to find a SellerInfo
   * @example
   * // Get one SellerInfo
   * const sellerInfo = await prisma.sellerInfo.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SellerInfoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SellerInfoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SellerInfoClient<runtime.Types.Result.GetResult<Prisma.$SellerInfoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SellerInfo that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellerInfoFindFirstArgs} args - Arguments to find a SellerInfo
   * @example
   * // Get one SellerInfo
   * const sellerInfo = await prisma.sellerInfo.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SellerInfoFindFirstArgs>(args?: Prisma.SelectSubset<T, SellerInfoFindFirstArgs<ExtArgs>>): Prisma.Prisma__SellerInfoClient<runtime.Types.Result.GetResult<Prisma.$SellerInfoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SellerInfo that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellerInfoFindFirstOrThrowArgs} args - Arguments to find a SellerInfo
   * @example
   * // Get one SellerInfo
   * const sellerInfo = await prisma.sellerInfo.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SellerInfoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SellerInfoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SellerInfoClient<runtime.Types.Result.GetResult<Prisma.$SellerInfoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SellerInfos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellerInfoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SellerInfos
   * const sellerInfos = await prisma.sellerInfo.findMany()
   * 
   * // Get first 10 SellerInfos
   * const sellerInfos = await prisma.sellerInfo.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sellerInfoWithIdOnly = await prisma.sellerInfo.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SellerInfoFindManyArgs>(args?: Prisma.SelectSubset<T, SellerInfoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SellerInfoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SellerInfo.
   * @param {SellerInfoCreateArgs} args - Arguments to create a SellerInfo.
   * @example
   * // Create one SellerInfo
   * const SellerInfo = await prisma.sellerInfo.create({
   *   data: {
   *     // ... data to create a SellerInfo
   *   }
   * })
   * 
   */
  create<T extends SellerInfoCreateArgs>(args: Prisma.SelectSubset<T, SellerInfoCreateArgs<ExtArgs>>): Prisma.Prisma__SellerInfoClient<runtime.Types.Result.GetResult<Prisma.$SellerInfoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SellerInfos.
   * @param {SellerInfoCreateManyArgs} args - Arguments to create many SellerInfos.
   * @example
   * // Create many SellerInfos
   * const sellerInfo = await prisma.sellerInfo.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SellerInfoCreateManyArgs>(args?: Prisma.SelectSubset<T, SellerInfoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SellerInfos and returns the data saved in the database.
   * @param {SellerInfoCreateManyAndReturnArgs} args - Arguments to create many SellerInfos.
   * @example
   * // Create many SellerInfos
   * const sellerInfo = await prisma.sellerInfo.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SellerInfos and only return the `id`
   * const sellerInfoWithIdOnly = await prisma.sellerInfo.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SellerInfoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SellerInfoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SellerInfoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SellerInfo.
   * @param {SellerInfoDeleteArgs} args - Arguments to delete one SellerInfo.
   * @example
   * // Delete one SellerInfo
   * const SellerInfo = await prisma.sellerInfo.delete({
   *   where: {
   *     // ... filter to delete one SellerInfo
   *   }
   * })
   * 
   */
  delete<T extends SellerInfoDeleteArgs>(args: Prisma.SelectSubset<T, SellerInfoDeleteArgs<ExtArgs>>): Prisma.Prisma__SellerInfoClient<runtime.Types.Result.GetResult<Prisma.$SellerInfoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SellerInfo.
   * @param {SellerInfoUpdateArgs} args - Arguments to update one SellerInfo.
   * @example
   * // Update one SellerInfo
   * const sellerInfo = await prisma.sellerInfo.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SellerInfoUpdateArgs>(args: Prisma.SelectSubset<T, SellerInfoUpdateArgs<ExtArgs>>): Prisma.Prisma__SellerInfoClient<runtime.Types.Result.GetResult<Prisma.$SellerInfoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SellerInfos.
   * @param {SellerInfoDeleteManyArgs} args - Arguments to filter SellerInfos to delete.
   * @example
   * // Delete a few SellerInfos
   * const { count } = await prisma.sellerInfo.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SellerInfoDeleteManyArgs>(args?: Prisma.SelectSubset<T, SellerInfoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SellerInfos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellerInfoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SellerInfos
   * const sellerInfo = await prisma.sellerInfo.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SellerInfoUpdateManyArgs>(args: Prisma.SelectSubset<T, SellerInfoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SellerInfos and returns the data updated in the database.
   * @param {SellerInfoUpdateManyAndReturnArgs} args - Arguments to update many SellerInfos.
   * @example
   * // Update many SellerInfos
   * const sellerInfo = await prisma.sellerInfo.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SellerInfos and only return the `id`
   * const sellerInfoWithIdOnly = await prisma.sellerInfo.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SellerInfoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SellerInfoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SellerInfoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SellerInfo.
   * @param {SellerInfoUpsertArgs} args - Arguments to update or create a SellerInfo.
   * @example
   * // Update or create a SellerInfo
   * const sellerInfo = await prisma.sellerInfo.upsert({
   *   create: {
   *     // ... data to create a SellerInfo
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SellerInfo we want to update
   *   }
   * })
   */
  upsert<T extends SellerInfoUpsertArgs>(args: Prisma.SelectSubset<T, SellerInfoUpsertArgs<ExtArgs>>): Prisma.Prisma__SellerInfoClient<runtime.Types.Result.GetResult<Prisma.$SellerInfoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SellerInfos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellerInfoCountArgs} args - Arguments to filter SellerInfos to count.
   * @example
   * // Count the number of SellerInfos
   * const count = await prisma.sellerInfo.count({
   *   where: {
   *     // ... the filter for the SellerInfos we want to count
   *   }
   * })
  **/
  count<T extends SellerInfoCountArgs>(
    args?: Prisma.Subset<T, SellerInfoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SellerInfoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SellerInfo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellerInfoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SellerInfoAggregateArgs>(args: Prisma.Subset<T, SellerInfoAggregateArgs>): Prisma.PrismaPromise<GetSellerInfoAggregateType<T>>

  /**
   * Group by SellerInfo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellerInfoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SellerInfoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SellerInfoGroupByArgs['orderBy'] }
      : { orderBy?: SellerInfoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SellerInfoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSellerInfoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SellerInfo model
 */
readonly fields: SellerInfoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SellerInfo.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SellerInfoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  property<T extends Prisma.SellerInfo$propertyArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SellerInfo$propertyArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SellerInfo model
 */
export interface SellerInfoFieldRefs {
  readonly id: Prisma.FieldRef<"SellerInfo", 'String'>
  readonly name: Prisma.FieldRef<"SellerInfo", 'String'>
  readonly email: Prisma.FieldRef<"SellerInfo", 'String'>
  readonly phone: Prisma.FieldRef<"SellerInfo", 'String'>
}
    

// Custom InputTypes
/**
 * SellerInfo findUnique
 */
export type SellerInfoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerInfo
   */
  select?: Prisma.SellerInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellerInfo
   */
  omit?: Prisma.SellerInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerInfoInclude<ExtArgs> | null
  /**
   * Filter, which SellerInfo to fetch.
   */
  where: Prisma.SellerInfoWhereUniqueInput
}

/**
 * SellerInfo findUniqueOrThrow
 */
export type SellerInfoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerInfo
   */
  select?: Prisma.SellerInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellerInfo
   */
  omit?: Prisma.SellerInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerInfoInclude<ExtArgs> | null
  /**
   * Filter, which SellerInfo to fetch.
   */
  where: Prisma.SellerInfoWhereUniqueInput
}

/**
 * SellerInfo findFirst
 */
export type SellerInfoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerInfo
   */
  select?: Prisma.SellerInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellerInfo
   */
  omit?: Prisma.SellerInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerInfoInclude<ExtArgs> | null
  /**
   * Filter, which SellerInfo to fetch.
   */
  where?: Prisma.SellerInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SellerInfos to fetch.
   */
  orderBy?: Prisma.SellerInfoOrderByWithRelationInput | Prisma.SellerInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SellerInfos.
   */
  cursor?: Prisma.SellerInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SellerInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SellerInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SellerInfos.
   */
  distinct?: Prisma.SellerInfoScalarFieldEnum | Prisma.SellerInfoScalarFieldEnum[]
}

/**
 * SellerInfo findFirstOrThrow
 */
export type SellerInfoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerInfo
   */
  select?: Prisma.SellerInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellerInfo
   */
  omit?: Prisma.SellerInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerInfoInclude<ExtArgs> | null
  /**
   * Filter, which SellerInfo to fetch.
   */
  where?: Prisma.SellerInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SellerInfos to fetch.
   */
  orderBy?: Prisma.SellerInfoOrderByWithRelationInput | Prisma.SellerInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SellerInfos.
   */
  cursor?: Prisma.SellerInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SellerInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SellerInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SellerInfos.
   */
  distinct?: Prisma.SellerInfoScalarFieldEnum | Prisma.SellerInfoScalarFieldEnum[]
}

/**
 * SellerInfo findMany
 */
export type SellerInfoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerInfo
   */
  select?: Prisma.SellerInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellerInfo
   */
  omit?: Prisma.SellerInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerInfoInclude<ExtArgs> | null
  /**
   * Filter, which SellerInfos to fetch.
   */
  where?: Prisma.SellerInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SellerInfos to fetch.
   */
  orderBy?: Prisma.SellerInfoOrderByWithRelationInput | Prisma.SellerInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SellerInfos.
   */
  cursor?: Prisma.SellerInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SellerInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SellerInfos.
   */
  skip?: number
  distinct?: Prisma.SellerInfoScalarFieldEnum | Prisma.SellerInfoScalarFieldEnum[]
}

/**
 * SellerInfo create
 */
export type SellerInfoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerInfo
   */
  select?: Prisma.SellerInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellerInfo
   */
  omit?: Prisma.SellerInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerInfoInclude<ExtArgs> | null
  /**
   * The data needed to create a SellerInfo.
   */
  data: Prisma.XOR<Prisma.SellerInfoCreateInput, Prisma.SellerInfoUncheckedCreateInput>
}

/**
 * SellerInfo createMany
 */
export type SellerInfoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SellerInfos.
   */
  data: Prisma.SellerInfoCreateManyInput | Prisma.SellerInfoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SellerInfo createManyAndReturn
 */
export type SellerInfoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerInfo
   */
  select?: Prisma.SellerInfoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SellerInfo
   */
  omit?: Prisma.SellerInfoOmit<ExtArgs> | null
  /**
   * The data used to create many SellerInfos.
   */
  data: Prisma.SellerInfoCreateManyInput | Prisma.SellerInfoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SellerInfo update
 */
export type SellerInfoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerInfo
   */
  select?: Prisma.SellerInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellerInfo
   */
  omit?: Prisma.SellerInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerInfoInclude<ExtArgs> | null
  /**
   * The data needed to update a SellerInfo.
   */
  data: Prisma.XOR<Prisma.SellerInfoUpdateInput, Prisma.SellerInfoUncheckedUpdateInput>
  /**
   * Choose, which SellerInfo to update.
   */
  where: Prisma.SellerInfoWhereUniqueInput
}

/**
 * SellerInfo updateMany
 */
export type SellerInfoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SellerInfos.
   */
  data: Prisma.XOR<Prisma.SellerInfoUpdateManyMutationInput, Prisma.SellerInfoUncheckedUpdateManyInput>
  /**
   * Filter which SellerInfos to update
   */
  where?: Prisma.SellerInfoWhereInput
  /**
   * Limit how many SellerInfos to update.
   */
  limit?: number
}

/**
 * SellerInfo updateManyAndReturn
 */
export type SellerInfoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerInfo
   */
  select?: Prisma.SellerInfoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SellerInfo
   */
  omit?: Prisma.SellerInfoOmit<ExtArgs> | null
  /**
   * The data used to update SellerInfos.
   */
  data: Prisma.XOR<Prisma.SellerInfoUpdateManyMutationInput, Prisma.SellerInfoUncheckedUpdateManyInput>
  /**
   * Filter which SellerInfos to update
   */
  where?: Prisma.SellerInfoWhereInput
  /**
   * Limit how many SellerInfos to update.
   */
  limit?: number
}

/**
 * SellerInfo upsert
 */
export type SellerInfoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerInfo
   */
  select?: Prisma.SellerInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellerInfo
   */
  omit?: Prisma.SellerInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerInfoInclude<ExtArgs> | null
  /**
   * The filter to search for the SellerInfo to update in case it exists.
   */
  where: Prisma.SellerInfoWhereUniqueInput
  /**
   * In case the SellerInfo found by the `where` argument doesn't exist, create a new SellerInfo with this data.
   */
  create: Prisma.XOR<Prisma.SellerInfoCreateInput, Prisma.SellerInfoUncheckedCreateInput>
  /**
   * In case the SellerInfo was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SellerInfoUpdateInput, Prisma.SellerInfoUncheckedUpdateInput>
}

/**
 * SellerInfo delete
 */
export type SellerInfoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerInfo
   */
  select?: Prisma.SellerInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellerInfo
   */
  omit?: Prisma.SellerInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerInfoInclude<ExtArgs> | null
  /**
   * Filter which SellerInfo to delete.
   */
  where: Prisma.SellerInfoWhereUniqueInput
}

/**
 * SellerInfo deleteMany
 */
export type SellerInfoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SellerInfos to delete
   */
  where?: Prisma.SellerInfoWhereInput
  /**
   * Limit how many SellerInfos to delete.
   */
  limit?: number
}

/**
 * SellerInfo.property
 */
export type SellerInfo$propertyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  where?: Prisma.PropertyWhereInput
}

/**
 * SellerInfo without action
 */
export type SellerInfoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerInfo
   */
  select?: Prisma.SellerInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellerInfo
   */
  omit?: Prisma.SellerInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerInfoInclude<ExtArgs> | null
}
